# Generated by Django 5.1.15 on 2026-05-03 21:02

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_commune_media"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#1a4d6e",
                        help_text="Couleur d'accent au format #RRGGBB",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nom d'icône Lucide (ex: 'Newspaper', 'Camera')",
                        max_length=40,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                (
                    "chapeau",
                    models.CharField(
                        blank=True, help_text="Accroche (max 300 car.)", max_length=300
                    ),
                ),
                ("body", models.TextField(help_text="Corps de l'article en markdown")),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="articles/%Y/%m/"),
                ),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("reportage", "Reportage"),
                            ("portrait", "Portrait"),
                            ("breve", "Brève"),
                            ("tribune", "Tribune libre"),
                            ("dossier", "Dossier"),
                        ],
                        db_index=True,
                        default="reportage",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("scheduled", "Programmé"),
                            ("published", "Publié"),
                            ("archived", "Archivé"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="À la une de la page d'accueil"),
                ),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("auto_publish_to_facebook", models.BooleanField(default=True)),
                ("facebook_post_id", models.CharField(blank=True, max_length=100)),
                ("facebook_published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sponsor_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Champ sponsor anticipé sprint 3-4 (FK Business à créer)",
                    ),
                ),
                (
                    "sponsor_disclosure",
                    models.CharField(
                        blank=True,
                        help_text="Mention obligatoire si sponsorisé (ex: 'En partenariat avec X')",
                        max_length=200,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="core.commune",
                    ),
                ),
                (
                    "gallery",
                    models.ManyToManyField(blank=True, related_name="articles", to="core.media"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="editorial.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="articles", to="editorial.tag"),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["status", "-published_at"], name="article_status_pub_idx"),
                    models.Index(fields=["category", "-published_at"], name="article_cat_pub_idx"),
                    models.Index(
                        fields=["commune", "-published_at"], name="article_commune_pub_idx"
                    ),
                ],
            },
        ),
    ]
