# Generated by Django 5.1.15 on 2026-05-04 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
        ("editorial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="sponsor",
            field=models.ForeignKey(
                blank=True,
                help_text="Commerçant sponsor de l'article (badge + CTA fiche)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sponsored_articles",
                to="directory.business",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="sponsor_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="DEPRECATED — données legacy à migrer vers FK sponsor",
            ),
        ),
    ]
