/* eslint-disable @next/next/no-img-element */
"use client";
import Link from "next/link";
import { useState, useTransition } from "react";
import { Check, ExternalLink, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import { apiFetch } from "@/lib/api";
import type { Commune, EventCategory, EventImportCandidate } from "@/types/api";
function csrf(){const match=document.cookie.match(/(?:^|; )csrftoken=([^;]+)/);return match?decodeURIComponent(match[1]):null;}
function date(value:string|null){return value?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Paris"}).format(new Date(value)):"Date manquante";}
export function EventImportsAdmin({initialCandidates,communes,categories}:{initialCandidates:EventImportCandidate[];communes:Commune[];categories:EventCategory[]}){
 const [rows,setRows]=useState(initialCandidates);const [message,setMessage]=useState<string|null>(null);const [pending,startTransition]=useTransition();
 const update=(id:number,field:"commune"|"category",value:string)=>setRows(current=>current.map(row=>row.id===id?{...row,[field]:value?Number(value):null}:row));
 const act=(row:EventImportCandidate,action:"approve"|"reject")=>startTransition(async()=>{let token=csrf();if(!token){await apiFetch("/api/auth/csrf/");token=csrf();}const response=await apiFetch(`/api/admin/event-imports/${row.id}/${action}/`,{method:"POST",headers:token?{"X-CSRFToken":token}:{},body:JSON.stringify(action==="approve"?{commune:row.commune,category:row.category}:{})});const payload=await response.json().catch(()=>null);if(!response.ok){setMessage(payload?.detail??JSON.stringify(payload)??"Action impossible");return;}setRows(current=>current.filter(item=>item.id!==row.id));setMessage(action==="approve"?`« ${row.title} » publié et synchronisé.`:`« ${row.title} » rejeté.`);});
 return <div><div className="mb-4"><Link href="/admin/agenda" className="text-sm text-slate-600">← Agenda</Link><h1 className="text-xl font-bold">Événements à valider</h1><p className="text-sm text-slate-500">Les données détectées restent en attente tant qu’elles ne sont pas approuvées. Vérifie notamment la date, le lieu et les droits sur l’image.</p></div>{message?<p className="mb-4 rounded-lg bg-blue-50 p-3 text-sm text-blue-900">{message}</p>:null}
 {rows.length===0?<div className="rounded-xl border border-dashed bg-white p-12 text-center text-sm text-slate-500">Aucun candidat en attente.</div>:<div className="space-y-4">{rows.map(row=><article key={row.id} className="grid overflow-hidden rounded-xl border bg-white shadow-sm md:grid-cols-[220px_minmax(0,1fr)]">{row.image_url?<img src={row.image_url} alt="" className="h-full min-h-48 w-full object-cover" referrerPolicy="no-referrer"/>:<div className="flex min-h-48 items-center justify-center bg-slate-100 text-xs text-slate-400">Pas d’image détectée</div>}<div className="p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-xs font-medium uppercase text-[#a8533a]">{row.source_label} · {row.extraction_method==="mistral"?"Extraction IA à vérifier":row.extraction_method==="ics"?"ICS":"JSON-LD"}</p><h2 className="font-serif text-xl font-semibold">{row.title}</h2><p className="mt-1 text-sm text-slate-600">{date(row.starts_at)} · {row.venue_name||row.address||"Lieu manquant"}</p></div><a href={row.source_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-xs text-[#1a4d6e] underline">Source officielle <ExternalLink className="h-3 w-3"/></a></div>{row.short_description?<p className="mt-3 line-clamp-3 text-sm text-slate-600">{row.short_description}</p>:null}{row.extraction_evidence.length?<blockquote className="mt-3 border-l-2 border-[#1a4d6e] pl-3 text-xs italic text-slate-600">Preuve détectée : « {row.extraction_evidence[0]} »</blockquote>:null}{row.validation_errors.length?<p className="mt-3 rounded bg-amber-50 p-2 text-xs text-amber-900">{row.validation_errors.join(" · ")}</p>:null}<div className="mt-4 grid gap-3 sm:grid-cols-2"><Select aria-label="Commune" value={row.commune??""} onChange={event=>update(row.id,"commune",event.target.value)}><option value="">Choisir la commune *</option>{communes.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select aria-label="Catégorie" value={row.category??""} onChange={event=>update(row.id,"category",event.target.value)}><option value="">Choisir la catégorie *</option>{categories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</Select></div><div className="mt-4 flex justify-end gap-2"><Button variant="secondary" disabled={pending} onClick={()=>act(row,"reject")}><X className="h-4 w-4"/> Rejeter</Button><Button disabled={pending||!row.commune||!row.category||!row.starts_at||!row.ends_at} onClick={()=>act(row,"approve")}><Check className="h-4 w-4"/> Approuver et publier</Button></div></div></article>)}</div>}</div>;
}
