"use client";
import Link from "next/link";
import { useState, useTransition } from "react";
import { Play, Plus, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { apiFetch } from "@/lib/api";
import type { Commune, EventCategory, EventSource } from "@/types/api";

type Draft = { label: string; connector: "json_ld" | "crawl4ai" | "ics"; source_url: string; website_url: string; commune: string; default_category: string; default_kind: "event" | "market"; max_pages: number; is_active: boolean; sync_images: boolean; rights_note: string };
const EMPTY: Draft = { label: "", connector: "json_ld", source_url: "", website_url: "", commune: "", default_category: "", default_kind: "event", max_pages: 30, is_active: true, sync_images: true, rights_note: "" };
function csrf() { const match = document.cookie.match(/(?:^|; )csrftoken=([^;]+)/); return match ? decodeURIComponent(match[1]) : null; }
function draftFrom(source: EventSource): Draft { return { label: source.label, connector: source.connector, source_url: source.source_url, website_url: source.website_url, commune: source.commune ? String(source.commune) : "", default_category: source.default_category ? String(source.default_category) : "", default_kind: source.default_kind, max_pages: source.max_pages, is_active: source.is_active, sync_images: source.sync_images, rights_note: source.rights_note }; }

export function EventSourcesAdmin({ initialSources, communes, categories }: { initialSources: EventSource[]; communes: Commune[]; categories: EventCategory[] }) {
 const [sources,setSources]=useState(initialSources); const [selected,setSelected]=useState<EventSource|null>(null); const [draft,setDraft]=useState<Draft>(EMPTY); const [message,setMessage]=useState<string|null>(null); const [pending,startTransition]=useTransition();
 const choose=(source:EventSource|null)=>{setSelected(source);setDraft(source?draftFrom(source):EMPTY);setMessage(null);};
 const request=(path:string, init:RequestInit={})=>startTransition(async()=>{let token=csrf();if(!token){await apiFetch("/api/auth/csrf/");token=csrf();}const response=await apiFetch(path,{...init,headers:{...(init.headers??{}),...(token?{"X-CSRFToken":token}:{})}});const payload=await response.json().catch(()=>null);if(!response.ok){setMessage(payload?.detail??JSON.stringify(payload)??"Action impossible");return;}setMessage("Action enregistrée.");if(path.endsWith("/run/")){setSources(rows=>rows.map(row=>row.id===selected?.id?{...row,last_status:"running"}:row));return;}const saved=payload as EventSource;setSources(rows=>rows.some(row=>row.id===saved.id)?rows.map(row=>row.id===saved.id?saved:row):[...rows,saved]);choose(saved);});
 const save=(event:React.FormEvent)=>{event.preventDefault();const body={...draft,commune:draft.commune?Number(draft.commune):null,default_category:draft.default_category?Number(draft.default_category):null};request(selected?`/api/admin/event-sources/${selected.id}/`:"/api/admin/event-sources/",{method:selected?"PATCH":"POST",body:JSON.stringify(body)});};
 return <div><div className="mb-4 flex items-center justify-between gap-3"><div><Link href="/admin/agenda" className="text-sm text-slate-600">← Agenda</Link><h1 className="text-xl font-bold">Sources officielles</h1><p className="text-sm text-slate-500">Connecteurs JSON-LD, Crawl4AI ou ICS. Chaque nouveau candidat passe obligatoirement par la validation admin.</p></div><Button size="sm" onClick={()=>choose(null)}><Plus className="h-4 w-4"/> Nouvelle</Button></div>
 <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_390px]"><div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-sm"><thead className="border-b bg-slate-50 text-left text-xs uppercase"><tr><th className="p-3">Source</th><th>Connecteur</th><th>État</th><th>À valider</th></tr></thead><tbody className="divide-y">{sources.map(source=><tr key={source.id} onClick={()=>choose(source)} className="cursor-pointer hover:bg-slate-50"><td className="p-3"><strong>{source.label}</strong><span className="block max-w-md truncate text-xs text-slate-400">{source.source_url}</span></td><td>{source.connector==="ics"?"ICS":source.connector==="crawl4ai"?"Crawl4AI":"JSON-LD"}</td><td>{source.last_status}</td><td>{source.pending_count}</td></tr>)}</tbody></table>{sources.length===0?<p className="p-8 text-center text-sm text-slate-500">Aucune source configurée.</p>:null}</div>
 <form onSubmit={save} className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">{selected?"Modifier la source":"Nouvelle source"}</h2>{message?<p className="rounded bg-blue-50 p-2 text-xs text-blue-900">{message}</p>:null}<div><Label>Nom *</Label><Input required value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}/></div><div><Label>Connecteur</Label><Select value={draft.connector} onChange={e=>setDraft({...draft,connector:e.target.value as Draft["connector"]})}><option value="json_ld">Pages web JSON-LD</option><option value="crawl4ai">Site JavaScript — Crawl4AI</option><option value="ics">Flux ICS</option></Select></div>{draft.connector==="crawl4ai"&&selected&&!selected.crawl4ai_available?<p className="rounded bg-amber-50 p-2 text-xs text-amber-900">Crawl4AI n’est pas configuré sur ce serveur : le crawler standard prendra automatiquement le relais. Si aucun JSON-LD n’est trouvé, aucune extraction Mistral ne sera lancée sans rendu exploitable.</p>:null}<div><Label>URL source *</Label><Input type="url" required value={draft.source_url} onChange={e=>setDraft({...draft,source_url:e.target.value})}/></div><div><Label>Site officiel</Label><Input type="url" value={draft.website_url} onChange={e=>setDraft({...draft,website_url:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><div><Label>Commune</Label><Select value={draft.commune} onChange={e=>setDraft({...draft,commune:e.target.value})}><option value="">Automatique</option>{communes.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</Select></div><div><Label>Catégorie</Label><Select value={draft.default_category} onChange={e=>setDraft({...draft,default_category:e.target.value})}><option value="">Automatique</option>{categories.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</Select></div></div><div><Label>Preuve / droit de réutilisation</Label><Input value={draft.rights_note} onChange={e=>setDraft({...draft,rights_note:e.target.value})} placeholder="Open data, accord écrit, flux public…"/></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={draft.is_active} onChange={e=>setDraft({...draft,is_active:e.target.checked})}/> Source active</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={draft.sync_images} onChange={e=>setDraft({...draft,sync_images:e.target.checked})}/> Actualiser automatiquement l’image officielle</label><Button type="submit" disabled={pending} className="w-full"><Save className="h-4 w-4"/> Enregistrer</Button>{selected?<Button type="button" variant="secondary" disabled={pending||!selected.is_active} className="w-full" onClick={()=>request(`/api/admin/event-sources/${selected.id}/run/`,{method:"POST"})}><Play className="h-4 w-4"/> Lancer maintenant</Button>:null}</form></div></div>;
}
