# Generated by Django 5.1.15 on 2026-05-03 21:02

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("insee_code", models.CharField(max_length=5, unique=True)),
                (
                    "postal_codes",
                    models.JSONField(
                        default=list, help_text="Liste des codes postaux (JSON array)"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        db_index=True, help_text='Code département : "30" ou "34"', max_length=3
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "bbox",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("short_description", models.CharField(blank=True, max_length=300)),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to="communes/")),
                ("intercommunalite", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Commune",
                "verbose_name_plural": "Communes",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.ImageField(upload_to="media/%Y/%m/")),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Texte alternatif accessibilité (obligatoire pour SEO)",
                        max_length=300,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=500)),
                (
                    "credit",
                    models.CharField(
                        blank=True, help_text="Crédit photo (auteur, source)", max_length=200
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("taken_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Média",
                "verbose_name_plural": "Médias",
                "ordering": ["-created_at"],
            },
        ),
    ]
