# Generated by Django 5.1.15 on 2026-10-01 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_commune_is_coastal_and_seed"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="geoclicMédia", max_length=60, verbose_name="Nom du site"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="le littoral camarguais",
                        max_length=120,
                        verbose_name="Accroche",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Format carré ou horizontal, fond transparent conseillé (PNG ou SVG converti).",
                        null=True,
                        upload_to="site/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#1a4d6e",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$",
                                "Couleur attendue au format #RRGGBB (ex : #1a4d6e).",
                            )
                        ],
                        verbose_name="Couleur principale",
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#a8533a",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$",
                                "Couleur attendue au format #RRGGBB (ex : #1a4d6e).",
                            )
                        ],
                        verbose_name="Couleur d'accent",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Réglages du site",
                "verbose_name_plural": "Réglages du site",
            },
        ),
    ]
