# Generated by Django 5.1.15 on 2026-07-26 22:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_commune_is_coastal_and_seed'),
        ('directory', '0003_business_is_local_producer'),
        ('editorial', '0002_article_sponsor_alter_article_sponsor_data'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#1a4d6e', max_length=7)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Catégorie Découvrir',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='places/%Y/%m/')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('duration', models.CharField(blank=True, max_length=80)),
                ('difficulty', models.CharField(blank=True, max_length=80)),
                ('accessibility', models.TextField(blank=True)),
                ('best_season', models.CharField(blank=True, max_length=120)),
                ('practical_info', models.TextField(blank=True)),
                ('official_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='core.commune')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_places', to=settings.AUTH_USER_MODEL)),
                ('gallery', models.ManyToManyField(blank=True, related_name='places', to='core.media')),
                ('related_articles', models.ManyToManyField(blank=True, related_name='related_places', to='editorial.article')),
                ('related_businesses', models.ManyToManyField(blank=True, related_name='related_places', to='directory.business')),
                ('related_events', models.ManyToManyField(blank=True, related_name='related_places', to='events.event')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='discovery.placecategory')),
            ],
            options={
                'ordering': ('sort_order', '-is_featured', 'title'),
                'indexes': [models.Index(fields=['status', 'category'], name='place_status_cat_idx'), models.Index(fields=['status', 'commune'], name='place_status_commune_idx')],
            },
        ),
    ]
