# Generated by Django 5.1.15 on 2026-07-29 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_signals_db_default'),
        ('core', '0003_commune_is_coastal_and_seed'),
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceImportCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_uid', models.CharField(max_length=240)),
                ('extraction_method', models.CharField(choices=[('ai', 'Extraction IA à valider'), ('json_ld', 'JSON-LD officiel')], db_index=True, default='ai', max_length=20)),
                ('source_url', models.URLField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('image_credit', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('duration', models.CharField(blank=True, max_length=80)),
                ('difficulty', models.CharField(blank=True, max_length=80)),
                ('accessibility', models.TextField(blank=True)),
                ('best_season', models.CharField(blank=True, max_length=120)),
                ('practical_info', models.TextField(blank=True)),
                ('official_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'À vérifier'), ('imported', 'Importé'), ('rejected', 'Rejeté'), ('duplicate', 'Doublon'), ('invalid', 'Incomplet')], db_index=True, default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_candidates', to='discovery.placecategory')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_import_candidates', to='core.commune')),
                ('crawl_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_import_candidates', to='assistant.crawlsource')),
                ('matched_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_candidates', to='discovery.place')),
            ],
            options={
                'verbose_name': 'Candidat Découvrir',
                'verbose_name_plural': 'Candidats Découvrir',
                'ordering': ['status', 'title'],
                'indexes': [models.Index(fields=['crawl_source', 'status'], name='place_cand_src_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('crawl_source', 'source_uid'), name='place_candidate_unique_source_uid')],
            },
        ),
    ]
