# Generated by Django 5.1.15 on 2026-05-04 09:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_commune_media"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nom d'icône Lucide (ex: 'UtensilsCrossed', 'Hotel')",
                        max_length=40,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "schema_type",
                    models.CharField(
                        default="LocalBusiness",
                        help_text="Type schema.org (LocalBusiness, Restaurant, Store, LodgingBusiness...)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="directory.businesscategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie commerçant",
                "verbose_name_plural": "Catégories commerçants",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("siret", models.CharField(blank=True, max_length=14)),
                ("short_description", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("specialties", models.JSONField(blank=True, default=list)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="businesses/logos/")),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="businesses/covers/"),
                ),
                ("address", models.CharField(max_length=255)),
                ("address_complement", models.CharField(blank=True, max_length=255)),
                ("postal_code", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=100)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                ("opening_hours", models.JSONField(blank=True, default=dict)),
                ("seasonal_closures", models.JSONField(blank=True, default=list)),
                (
                    "plan",
                    models.CharField(
                        choices=[("free", "Gratuit"), ("basic", "Basic"), ("premium", "Premium")],
                        db_index=True,
                        default="free",
                        max_length=20,
                    ),
                ),
                ("plan_starts_at", models.DateTimeField(blank=True, null=True)),
                ("plan_ends_at", models.DateTimeField(blank=True, null=True)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=100)),
                ("stripe_subscription_id", models.CharField(blank=True, max_length=100)),
                ("is_claimed", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="businesses",
                        to="core.commune",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="businesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photos",
                    models.ManyToManyField(blank=True, related_name="businesses", to="core.media"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="businesses",
                        to="directory.businesscategory",
                    ),
                ),
                (
                    "secondary_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="secondary_businesses",
                        to="directory.businesscategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commerçant",
                "verbose_name_plural": "Commerçants",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["commune", "category"], name="biz_commune_cat_idx"),
                    models.Index(fields=["is_published", "plan"], name="biz_pub_plan_idx"),
                    models.Index(fields=["plan", "plan_ends_at"], name="biz_plan_end_idx"),
                ],
            },
        ),
    ]
