# Generated by Django 5.1.15 on 2026-05-04 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_commune_media"),
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="service_areas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Zones supplémentaires desservies (artisans multi-communes, services à domicile…).",
                related_name="serving_businesses",
                to="core.commune",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="commune",
            field=models.ForeignKey(
                help_text="Commune où est physiquement implanté le commerce (géoloc).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="businesses",
                to="core.commune",
            ),
        ),
    ]
