# Generated by Django 5.1.15 on 2026-07-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_business_service_areas_alter_business_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_local_producer',
            field=models.BooleanField(db_index=True, default=False, help_text='Affiche cette fiche dans le module Marchés & producteurs.'),
        ),
    ]
