# Generated by Django 5.1.15 on 2026-09-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0005_alter_businessimportcandidate_image_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businessimportcandidate",
            options={
                "ordering": ["status", "name"],
                "verbose_name": "Candidat Commerçant",
                "verbose_name_plural": "Candidats Commerçants",
            },
        ),
        migrations.AlterField(
            model_name="businessimportcandidate",
            name="extraction_method",
            field=models.CharField(
                choices=[("ai", "Extraction IA à valider"), ("json_ld", "JSON-LD officiel")],
                db_index=True,
                default="ai",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="businessimportcandidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "À vérifier"),
                    ("imported", "Importé"),
                    ("rejected", "Rejeté"),
                    ("duplicate", "Doublon"),
                    ("invalid", "Incomplet"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
