# Generated by Django 5.1.15 on 2026-10-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0006_fix_french_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="pending_changes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="pending_cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="businesses/pending/"),
        ),
        migrations.AddField(
            model_name="business",
            name="pending_logo",
            field=models.ImageField(blank=True, null=True, upload_to="businesses/pending/"),
        ),
        migrations.AddField(
            model_name="business",
            name="pending_submitted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
