# Generated by Django 5.1.15 on 2026-05-04 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_commune_media"),
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom interne pour identifier la campagne (ex: 'Hipolem été 2026 — sidebar accueil')",
                        max_length=150,
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("home_hero", "Page d'accueil — Hero"),
                            ("home_sidebar", "Page d'accueil — Sidebar"),
                            ("article_inline", "Article — Inline"),
                            ("article_sidebar", "Article — Sidebar"),
                            ("directory_top", "Annuaire — Top"),
                            ("directory_inline", "Annuaire — Inline"),
                            ("agenda_top", "Agenda — Top"),
                            ("newsletter", "Newsletter"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("image", models.ImageField(upload_to="ads/")),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        help_text="Titre court affiché sur l'encart (max 80 car).",
                        max_length=80,
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True,
                        help_text="Texte du bouton (ex: 'Découvrir', 'Réserver').",
                        max_length=30,
                    ),
                ),
                (
                    "target_url",
                    models.URLField(
                        help_text="URL de destination quand l'utilisateur clique sur l'encart."
                    ),
                ),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField(db_index=True)),
                (
                    "price_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Prix payé pour cette campagne (HT, en EUR).",
                        max_digits=8,
                    ),
                ),
                ("impression_count", models.PositiveIntegerField(default=0)),
                ("click_count", models.PositiveIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Active = peut être servie. Désactiver pour suspendre temporairement.",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False,
                        help_text="Paiement reçu (pour la phase pilote gratuite, laisser à False).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="directory.business",
                    ),
                ),
                (
                    "target_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Catégories ciblées (vide = toutes).",
                        related_name="targeted_campaigns",
                        to="directory.businesscategory",
                    ),
                ),
                (
                    "target_communes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Communes ciblées (vide = toutes).",
                        related_name="targeted_campaigns",
                        to="core.commune",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagne publicitaire",
                "verbose_name_plural": "Campagnes publicitaires",
                "ordering": ["-starts_at"],
                "indexes": [
                    models.Index(
                        fields=["placement", "is_active", "starts_at", "ends_at"],
                        name="ads_serve_lookup_idx",
                    ),
                    models.Index(fields=["business", "-starts_at"], name="ads_business_idx"),
                ],
            },
        ),
    ]
