# Generated by Django 5.1.15 on 2026-08-01 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_weather_placements'),
        ('events', '0008_alter_eventimportcandidate_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='featured_event',
            field=models.ForeignKey(blank=True, help_text="Événement mis en avant dans le bandeau 'À la une'. Vide = créa classique (image + headline). Si renseigné, le bandeau affiche la fiche de l'événement et le clic renvoie vers sa page (target_url ignorée).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_campaigns', to='events.event'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='placement',
            field=models.CharField(choices=[('home_hero', "Page d'accueil — Hero"), ('home_sidebar', "Page d'accueil — Sidebar"), ('article_inline', 'Article — Inline'), ('article_sidebar', 'Article — Sidebar'), ('directory_top', 'Annuaire — Top'), ('directory_inline', 'Annuaire — Inline'), ('agenda_top', 'Agenda — Top'), ('agenda_featured', 'Agenda — À la une'), ('weather_top', 'Météo — Top'), ('weather_sidebar', 'Météo — Sidebar'), ('newsletter', 'Newsletter')], db_index=True, max_length=30),
        ),
    ]
