# Generated by Django 5.1.15 on 2026-08-01 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_adcampaign_featured_event_alter_adcampaign_placement'),
        ('directory', '0005_alter_businessimportcandidate_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='featured_business',
            field=models.ForeignKey(blank=True, help_text="Commerçant mis en avant dans le bandeau 'Annuaire — À la une'. Vide = créa classique. Si renseigné, le bandeau affiche la fiche du commerçant et le clic renvoie vers sa page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_campaigns', to='directory.business'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='placement',
            field=models.CharField(choices=[('home_hero', "Page d'accueil — Hero"), ('home_sidebar', "Page d'accueil — Sidebar"), ('article_inline', 'Article — Inline'), ('article_sidebar', 'Article — Sidebar'), ('directory_top', 'Annuaire — Top'), ('directory_inline', 'Annuaire — Inline'), ('directory_featured', 'Annuaire — À la une'), ('agenda_top', 'Agenda — Top'), ('agenda_featured', 'Agenda — À la une'), ('weather_top', 'Météo — Top'), ('weather_sidebar', 'Météo — Sidebar'), ('newsletter', 'Newsletter')], db_index=True, max_length=30),
        ),
    ]
