# Generated by Django 5.1.15 on 2026-07-26 21:49

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_commune_is_coastal_and_seed'),
        ('directory', '0002_business_service_areas_alter_business_commune'),
        ('editorial', '0002_article_sponsor_alter_article_sponsor_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#1a4d6e', max_length=7)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': "Catégorie d'événement",
                'verbose_name_plural': "Catégories d'événements",
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/')),
                ('kind', models.CharField(choices=[('event', 'Événement'), ('market', 'Marché')], db_index=True, default='event', max_length=20)),
                ('venue_name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('booking_url', models.URLField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('organizer', models.CharField(blank=True, max_length=150)),
                ('official_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('cancelled', 'Annulé'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='directory.business')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.commune')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('related_articles', models.ManyToManyField(blank=True, related_name='related_events', to='editorial.article')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventcategory')),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EventOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Prévue'), ('cancelled', 'Annulée'), ('postponed', 'Reportée')], db_index=True, default='scheduled', max_length=20)),
                ('note', models.CharField(blank=True, help_text='Information propre à cette date : déplacement, annulation…', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='events.event')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'kind'], name='event_status_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['commune', 'status'], name='event_commune_status_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'status'], name='event_cat_status_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoccurrence',
            index=models.Index(fields=['status', 'starts_at', 'ends_at'], name='event_occ_status_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventoccurrence',
            constraint=models.UniqueConstraint(fields=('event', 'starts_at'), name='event_occurrence_unique_start'),
        ),
        migrations.AddConstraint(
            model_name='eventoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='event_occurrence_end_after_start'),
        ),
    ]
