# Generated by Django 5.1.15 on 2026-07-28 20:20

from django.db import migrations, models


def rename_mistral_candidates(apps, schema_editor):
    EventImportCandidate = apps.get_model("events", "EventImportCandidate")
    EventImportCandidate.objects.filter(extraction_method="mistral").update(
        extraction_method="ai"
    )


def restore_mistral_candidates(apps, schema_editor):
    EventImportCandidate = apps.get_model("events", "EventImportCandidate")
    EventImportCandidate.objects.filter(extraction_method="ai").update(
        extraction_method="mistral"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventsource_connector_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsource',
            name='ai_completed_parts',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='eventsource',
            name='ai_extraction_cache',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='eventsource',
            name='ai_failed_parts',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='eventsource',
            name='ai_model',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='eventsource',
            name='ai_provider',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='eventsource',
            name='ai_total_parts',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(
            rename_mistral_candidates,
            restore_mistral_candidates,
        ),
        migrations.AlterField(
            model_name='eventimportcandidate',
            name='extraction_method',
            field=models.CharField(choices=[('json_ld', 'JSON-LD officiel'), ('ai', 'Extraction IA à valider'), ('ics', 'Flux ICS officiel')], db_index=True, default='json_ld', max_length=20),
        ),
    ]
