# Generated by Django 5.1.15 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_eventsource_ai_completed_parts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventimportrun",
            name="expired_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="eventimportcandidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "À vérifier"),
                    ("imported", "Importé"),
                    ("rejected", "Rejeté"),
                    ("duplicate", "Doublon"),
                    ("invalid", "Incomplet"),
                    ("expired", "Expiré"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
