# Generated by Django 5.1.15 on 2026-07-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimportcandidate',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventimportcandidate',
            name='source_url',
            field=models.URLField(max_length=1000),
        ),
    ]
