# Generated by Django 5.1.15 on 2026-07-30 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0006_crawlsource_multi_extraction_cache'),
        ('core', '0003_commune_is_coastal_and_seed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Nom d'icÃ´ne Lucide (ex: 'Briefcase', 'House').", max_length=50)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': "CatÃ©gorie d'annonce",
                'verbose_name_plural': "CatÃ©gories d'annonces",
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('locality', models.CharField(blank=True, help_text="LocalitÃ© brute si la commune n'est pas rÃ©solue (ex: Â« Terre de Camargue Â»).", max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('employer_or_agency', models.CharField(blank=True, help_text='Employeur, agence ou contact affichÃ©.', max_length=150)),
                ('contract_type', models.CharField(blank=True, help_text='Type de contrat (CDI, CDD, saisonnier...) ou de bail.', max_length=80)),
                ('price', models.CharField(blank=True, help_text='Salaire, loyer ou prix affichÃ© (texte libre).', max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('application_url', models.URLField(blank=True, help_text="Lien pour postuler ou voir l'annonce d'origine.")),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'PubliÃ©e'), ('expired', 'ExpirÃ©e'), ('archived', 'ArchivÃ©e')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text="Date de fin de validitÃ© ; l'annonce bascule en expirÃ©e.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(blank=True, help_text='Commune concernÃ©e ; NULL = annonce intercommunale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='core.commune')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_listings', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.listingcategory')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ('-published_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ListingImportCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_uid', models.CharField(max_length=240)),
                ('extraction_method', models.CharField(choices=[('ai', 'Extraction IA Ã\xa0 valider'), ('json_ld', 'JSON-LD officiel')], db_index=True, default='ai', max_length=20)),
                ('source_url', models.URLField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('locality', models.CharField(blank=True, max_length=120)),
                ('employer_or_agency', models.CharField(blank=True, max_length=150)),
                ('contract_type', models.CharField(blank=True, max_length=80)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('application_url', models.URLField(blank=True)),
                ('published_on_source_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ã€ vÃ©rifier'), ('imported', 'ImportÃ©e'), ('rejected', 'RejetÃ©e'), ('duplicate', 'Doublon'), ('invalid', 'IncomplÃ¨te')], db_index=True, default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_candidates', to='listings.listingcategory')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_import_candidates', to='core.commune')),
                ('crawl_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_import_candidates', to='assistant.crawlsource')),
                ('matched_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_candidates', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Candidat annonce',
                'verbose_name_plural': 'Candidats annonces',
                'ordering': ['status', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'category'], name='listing_status_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'expires_at'], name='listing_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimportcandidate',
            index=models.Index(fields=['crawl_source', 'status'], name='listing_cand_src_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='listingimportcandidate',
            constraint=models.UniqueConstraint(fields=('crawl_source', 'source_uid'), name='listing_candidate_unique_source_uid'),
        ),
    ]
