# Generated by Django 5.1.15 on 2026-07-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='application_url',
            field=models.URLField(blank=True, help_text="Lien pour postuler ou voir l'annonce d'origine.", max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='listingimportcandidate',
            name='application_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='listingimportcandidate',
            name='source_url',
            field=models.URLField(max_length=1000),
        ),
    ]
