# Generated by Django 5.1.15 on 2026-09-30 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_commune_is_coastal_and_seed"),
        ("listings", "0003_fix_offres_d_emploi_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listingcategory",
            options={
                "ordering": ("sort_order", "name"),
                "verbose_name": "Catégorie d'annonce",
                "verbose_name_plural": "Catégories d'annonces",
            },
        ),
        migrations.AlterField(
            model_name="listing",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                help_text="Commune concernée ; NULL = annonce intercommunale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="core.commune",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="employer_or_agency",
            field=models.CharField(
                blank=True, help_text="Employeur, agence ou contact affiché.", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date de fin de validité ; l'annonce bascule en expirée.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="locality",
            field=models.CharField(
                blank=True,
                help_text="Localité brute si la commune n'est pas résolue (ex: « Terre de Camargue »).",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.CharField(
                blank=True,
                help_text="Salaire, loyer ou prix affiché (texte libre).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("published", "Publiée"),
                    ("expired", "Expirée"),
                    ("archived", "Archivée"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="listingcategory",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Nom d'icône Lucide (ex: 'Briefcase', 'House').",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="listingimportcandidate",
            name="extraction_method",
            field=models.CharField(
                choices=[("ai", "Extraction IA à valider"), ("json_ld", "JSON-LD officiel")],
                db_index=True,
                default="ai",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="listingimportcandidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "À vérifier"),
                    ("imported", "Importée"),
                    ("rejected", "Rejetée"),
                    ("duplicate", "Doublon"),
                    ("invalid", "Incomplète"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
