# Generated by Django 5.1.15 on 2026-07-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_signals_db_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlsource',
            name='multi_extraction_cache',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Cache de la passe IA multi-categories : {cle_segment: {events, markets, places}}. Une page n est renvoyee a l IA que si son contenu (ou le prompt/provider) a change depuis la derniere analyse.'),
        ),
    ]
