# Generated by Django 5.1.15 on 2026-07-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_crawlsource_multi_extraction_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgechunk',
            name='source_url',
            field=models.URLField(blank=True, help_text="URL d'origine pour citer la source dans la réponse.", max_length=1000),
        ),
    ]
